function dif=BinomialSum(valeq,valne,order,F)
% This function requres precalculated valeq and valne matrices
% It outputs what I call gamma in the notes
    npts=length(valeq);
    dif=zeros(2,2,2,2,npts);  
    for a1=1:2
        for a2=1:2
            for a3=1:2
                for a4=1:2
                    aspace=[a1,a2,a3,a4];
                    apath=aspace(order); %reorder alphas into new order
                    FV=[F(apath(1)),F(apath(2)),F(apath(3)),F(apath(4))];
                    Delta=[apath(1)==apath(2),apath(2)==apath(3),apath(3)==apath(4)]*2-1;  % +1 is same, -1 if different
                    
                    bin1=[FV(2),Delta(1)*(1-FV(1))]; % bin stands for binomial
                    bin2=[FV(3),Delta(2)*(1-FV(2))];
                    bin3=[FV(4),Delta(3)*(1-FV(3))];
                    
                    dif(a1,a2,a3,a4,:)=reshape(dif(a1,a2,a3,a4,:),[npts,1])+valeq*FV(1).*reshape(...
                        bin1(1)*bin2(1)*bin3(1)*valne(1,1,1,:)+...
                        bin1(1)*bin2(1)*bin3(2)*valne(1,1,2,:)+...
                        bin1(1)*bin2(2)*bin3(1)*valne(1,2,1,:)+...
                        bin1(1)*bin2(2)*bin3(2)*valne(1,2,2,:)+...
                        bin1(2)*bin2(1)*bin3(1)*valne(2,1,1,:)+...
                        bin1(2)*bin2(1)*bin3(2)*valne(2,1,2,:)+... 
                        bin1(2)*bin2(2)*bin3(1)*valne(2,2,1,:)+...
                        bin1(2)*bin2(2)*bin3(2)*valne(2,2,2,:),[npts,1]);
%{                    
%                     dif2=SDEL(a1,a2,a3,a4)*...
%                     valeq*(FV(A1)*FV(A2)             *FV(A3)             *FV(A4)             *valne(1,1,1)+...
%                            FV(A1)*FV(A2)             *FV(A3)             *Delta(3)*(1-FV(A3))*valne(1,1,2)+...
%                            FV(A1)*FV(A2)             *Delta(2)*(1-FV(A2))*FV(A4)             *valne(1,2,1)+...
%                            FV(A1)*FV(A2)             *Delta(2)*(1-FV(A2))*Delta(3)*(1-FV(A3))*valne(1,2,2)+...
%                            FV(A1)*Delta(1)*(1-FV(A1))*FV(A3)             *FV(A4)             *valne(2,1,1)+...
%                            FV(A1)*Delta(1)*(1-FV(A1))*FV(A3)             *Delta(3)*(1-FV(A3))*valne(2,1,2)+...
%                            FV(A1)*Delta(1)*(1-FV(A1))*Delta(2)*(1-FV(A2))*FV(A4)             *valne(2,2,1)+...
%                            FV(A1)*Delta(1)*(1-FV(A1))*Delta(2)*(1-FV(A2))*Delta(3)*(1-FV(A3))*valne(2,2,2));

                    DF=[1,-1];
                    FV=[F(a1),F(a2),F(a3),F(a4)];
                    DFV=[DF(a1),DF(a2),DF(a3),DF(a4)];
                    
                    A1=order(1);A2=order(2);A3=order(3);A4=order(4);
                    
                    difOld=1*...  used to have SDEL(a1,a2,a3,a4)
                      valeq*(FV(A1)*FV(A2)*FV(A3)*FV(A4)*valne(1,1,1)+...
                           FV(A1)*FV(A2)*FV(A3)*DFV(A3)*DFV(A4)*(1-FV(A3))*valne(1,1,2)+...
                           FV(A1)*FV(A2)*DFV(A2)*DFV(A3)*(1-FV(A2))*FV(A4)*valne(1,2,1)+...
                           FV(A1)*FV(A2)*DFV(A2)*DFV(A3)*(1-FV(A2))*DFV(A3)*DFV(A4)*(1-FV(A3))*valne(1,2,2)+...
                           FV(A1)*DFV(A1)*DFV(A2)*(1-FV(A1))*FV(A3)*FV(A4)*valne(2,1,1)+...
                           FV(A1)*DFV(A1)*DFV(A2)*(1-FV(A1))*FV(A3)*DFV(A3)*DFV(A4)*(1-FV(A3))*valne(2,1,2)+...
                           FV(A1)*DFV(A1)*DFV(A2)*(1-FV(A1))*DFV(A2)*DFV(A3)*(1-FV(A2))*FV(A4)*valne(2,2,1)+...
                           FV(A1)*DFV(A1)*DFV(A2)*(1-FV(A1))*DFV(A2)*DFV(A3)*(1-FV(A2))*DFV(A3)*DFV(A4)*(1-FV(A3))*valne(2,2,2));
                    
                    if abs((dif - difOld)/difOld)>10^-13  && ~isnan(difOld)
                        
                        format long
                        FV(A1)* bin1(1)*bin2(1)*bin3(2)
                        FV(A1)*FV(A2)*FV(A3)*DFV(A3)*DFV(A4)*(1-FV(A3))
                        
                        dif
                        difOld
                        order
                        [a1,a2,a3,a4]
                        error('dif ~= difOld')
                    end
%}                        
                    %S4(a1,a2,a3,a4)=S4(a1,a2,a3,a4)+dif;
                end
            end
        end
    end
end