function out=chicken(a,b,c,NM)
  out=(-NM^3*(NM*(a+b)+4)*c^4 ...
     -4*NM^2*(NM*(a+b)+3)*c^3 ...
    -12*NM^1*(NM*(a+b)+2)*c^2 ...
    +24*(expl(1,NM*c)-NM*(a+b))*c ...
    +24*expl(1,NM*c)*(a+b))/(24*c^5);
end